name: Debug for calling workflow

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deploy stage'
        required: true
        default: 'prd'
        type: choice
        options:
          - dev
          - stg
          - prd    

jobs:
  build_and_deploy_app:
    permissions:
      id-token: write
      contents: read    
    uses: katonobu/weather-chart-viewer-astro-sidey/.github/workflows/build_and_deploy.yaml@main
    with:
      stage: ${{ github.event.inputs.stage }}      