name: Run get_short_range_prediction

on:
    workflow_dispatch: # 手動実行を許可
    schedule:
      - cron: '0 19 * * *' # 日本時間 4:00 (UTC 19:00)
      - cron: '0 7 * * *'  # 日本時間 16:00 (UTC 7:00)

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # OIDCトークン発行に必要
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install boto3

      - name: Set timestamp
        run: echo "FETCH_DATE_TIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Run Python script
        run: python -m scraper.jobs.get_short_range_prediction

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: short-range-output_${{ env.FETCH_DATE_TIME }}
          path: scraper/data/**/*
          retention-days: 15

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::382736933734:role/weatherchart-contents-deploy-role          
          aws-region: ap-northeast-1

      - name: Upload artifacts to S3
        run: aws s3 cp scraper/data/ s3://frontend-cmn-weatherchart-content/shared/services/weatherchart/ --recursive

      - name: Generate directory list JSON (Python)
        env:
            BUCKET: frontend-cmn-weatherchart-content
            PREFIX: shared/services/weatherchart/
        run: |
            python util/generate_directory_list.py

      - name: Upload directory_list.json
        run: |
            aws s3 cp directory_list.json \
            s3://frontend-cmn-weatherchart-content/shared/services/weatherchart/directory_list.json

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1JJPY985HNT3W
            --paths "/shared/services/weatherchart/directory_list.json"

